### Pascal VOC Format

Create XML files in the Pascal VOC Format for the SMALL TRAIN+TEST

In [6]:
import pandas as pd
import numpy as np
import ast
import os
from pascal_voc_writer import Writer

Read text file with annotations

In [7]:
ann = pd.read_csv('annotated.txt',header=None)
ann

                        0    1    2    3    4  5
0      19430_20090614.jpg    0    0    0    0  0
1      13263_20130804.jpg    0    0    0    0  0
2       1444_20111220.jpg    0    0    0    0  0
3      13432_19961230.jpg    0    0    0    0  0
4      19019_20160523.jpg  648  740   98  178  1
5      13416_20061230.jpg    0    0    0    0  0
6      13306_20111230.jpg    0    0    0    0  0
7      17631_20160611.jpg    0    0    0    0  0
8      19333_20150728.jpg    0    0    0    0  0
9       1480_20150402.jpg    0    0    0    0  0
10     19509_20160726.jpg    0    0    0    0  0
11     19088_20100415.jpg    0    0    0    0  0
12     19294_20130223.jpg    0    0    0    0  0
13     13468_19911230.jpg    0    0    0    0  0
14      1467_20150731.jpg    0    0    0    0  0
15     12665_20130226.jpg  759  877  376  460  1
16     18926_20140529.jpg  601  687  419  507  1
17     13344_20041230.jpg    0    0    0    0  0
18     19484_20130822.jpg    0    0    0    0  0
19      1438_20140930.jpg  630  714  301  369  1
20     13380_20161230.jpg    0    0    0    0  0
21     19285_20030317.jpg    0    0    0    0  0
22     19498_20160814.jpg    0    0    0    0  0
23      1924_20120129.jpg  524  638  358  446  1
24      1454_20160804.jpg  606  688  455  517  1
25     13246_19941230.jpg    0    0    0    0  0
26     17481_20180417.jpg    0    0    0    0  0
27     17992_20030411.jpg    0    0    0    0  0
28     17378_19861230.jpg    0    0    0    0  0
29     14806_20160722.jpg    0    0    0    0  0
...                   ...  ...  ...  ...  ... ..
14609  13469_19941230.jpg    0    0    0    0  0
14610  13347_20021230.jpg    0    0    0    0  0
14611  19212_20131203.jpg  697  799  528  614  1
14612  17962_19961230.jpg    0    0    0    0  0
14613  17932_20090805.jpg    0    0    0    0  0
14614   1503_20160414.jpg    0    0    0    0  0
14615   1789_20161029.jpg  503  575  446  536  1
14616   1481_20101107.jpg    0    0    0    0  0
14617   1481_20170823.jpg  659  719  430  508  1
14618  19533_20160713.jpg    0    0    0    0  0
14619   1538_20140713.jpg    0    0    0    0  0
14620  19393_20160414.jpg    0    0    0    0  0
14621  19112_20170218.jpg  660  772  415  513  1
14622  18940_20130508.jpg    0    0    0    0  0
14623  13464_20160906.jpg    0    0    0    0  0
14624   1868_20180421.jpg  746  838  744  836  1
14625   2018_20170717.jpg  458  542  201  329  1
14626  17721_20160610.jpg    0    0    0    0  0
14627  19142_20091230.jpg    0    0    0    0  0
14628  19004_20101102.jpg    0    0    0    0  0
14629   1538_20160402.jpg    0    0    0    0  0
14630  19489_20080806.jpg    0    0    0    0  0
14631  18958_19691231.jpg    0    0    0    0  0
14632   1467_20160723.jpg    0    0    0    0  0
14633  19080_20170522.jpg  508  620  186  270  1
14634   1582_20140609.jpg    0    0    0    0  0
14635  18703_20101107.jpg    0    0    0    0  0
14636  13317_19951230.jpg    0    0    0    0  0
14637  19331_20150710.jpg    0    0    0    0  0
14638   1409_20110902.jpg  810  872  187  263  1

[14639 rows x 6 columns]

Obtain train and test file names

In [8]:
train = [f for f in os.listdir("train/") if f.endswith('.jpg')]
test = [f for f in os.listdir("test/") if f.endswith('.jpg')]

Create XML for train

In [9]:
ann_train = ann[ann[0].isin(train)]

for r in range(len(ann_train)):
    # Writer(path, width, height)
    writer = Writer("train/" + ann_train.iloc[r, 0], 1501, 944)

    # ::addObject(name, xmin, ymin, xmax, ymax)
    writer.addObject(ann_train.iloc[r, 5], ann_train.iloc[r, 1], ann_train.iloc[r, 2], ann_train.iloc[r, 3], ann_train.iloc[r, 4])

    # ::save(path)
    writer.save("train/" + ann_train.iloc[r, 0][:-4] + ".xml")

Create XML for test

In [11]:
ann_test = ann[ann[0].isin(test)]

for r in range(len(ann_test)):
    # Writer(path, width, height)
    writer = Writer("test/" + ann_test.iloc[r, 0], 1501, 944)

    # ::addObject(name, xmin, ymin, xmax, ymax)
    writer.addObject(ann_test.iloc[r, 5], ann_test.iloc[r, 1], ann_test.iloc[r, 2], ann_test.iloc[r, 3], ann_test.iloc[r, 4])

    # ::save(path)
    writer.save("test/" + ann_test.iloc[r, 0][:-4] + ".xml")